####
# GitLab CI
####

# Image
image: adoptopenjdk/openjdk11:jdk-11.28-alpine

services:
- docker:dind

variables:
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

# Stages
stages:
- build
- test
- publish

# Before Script
before_script:
- chmod +x gradlew

# Build
Assemble:
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    paths:
    - build/libs
    expire_in: 1 week

# Test
Run Tests:
  stage: test
  script:
  - ./gradlew test

# Docker
Publish Container Image:
  image: docker:stable
  stage: publish
  script:
  - cp build/libs/*.jar docker/rootfs/app.jar
  - docker build -t $CI_REGISTRY_IMAGE/cli:$CI_COMMIT_REF_SLUG docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
