####
# GitLab CI
####

# Image
image: openjdk:11-jdk-stretch

services:
- docker:dind

variables:
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

# Stages
stages:
- build

# Before Script
before_script:
- chmod +x gradlew

# Build
Docker Container - ARMv7:
  image: docker.io/arm32v7/openjdk:11-jdk-stretch
  stage: build
  script:
  - ./gradlew assemble
  - cp build/libs/*.jar docker/rootfs/app.jar
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-armv7 docker --file Dockerfile.armv7
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-armv7
  tags:
  - armhf
  artifacts:
    paths:
    - build/libs
    expire_in: 1 week

# Build
Docker Container - AMD64:
  image: openjdk:11-jdk-stretch
  stage: build
  script:
  - ./gradlew assemble
  - cp build/libs/*.jar docker/rootfs/app.jar
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG docker --file Dockerfile.amd64
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
    - build/libs
    expire_in: 1 week
